# Basic
title: 优三帝同学
subtitle: 上善若水，人淡如菊
welcome_message: <a href="https://u3dc.com/">欢迎访问我的博客~</a>
description: 嗨，我是优三帝 (@onevcat)，一名 Unity 开发者。
creator: <a href="https://u3dc.com">@u3dc</a>

url: "https://u3dc.github.io/"


permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: '//onev.cat'}
    - {title: 工具, description: 我所使用的 app 们, url: '/apps'}
    - {title: 订阅, description: 邮件订阅本站, url: '//objccn.io/subscribe'}

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    disqus: onevcat
    # duoshuo:
# Social
social:
    weibo: showpo
    github: u3dc
    twitter: GeeScan
    gplus: #
    mail: mark@u3dc.com

# Google Analytics
ga:
    id: UA-25719337-1
    host: onevcat.com
